/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jnitest_memutils_memcheck */

#ifndef _Included_com_jnitest_memutils_memcheck
#define _Included_com_jnitest_memutils_memcheck
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnitest_memutils_memcheck
 * Method:    doTask
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jnitest_memutils_memcheck_doTask
  (JNIEnv *, jobject, jint);

int check(char set, int no);
int setArea(char value);
int doTask();
int dumpMem(char *str, int num);

#ifdef __cplusplus
}
#endif
#endif
